#!/bin/bash
set -e

rm -rf /tmp/p
mkdir /tmp/p
/lib/systemd/system-generators/systemd-crontab-generator /tmp/p

rm -rf /tmp/c
mkdir /tmp/c
./systemd-crontab-generator /tmp/c
colordiff -Nur /tmp/p /tmp/c
